<a href="https://colab.research.google.com/github/udayPatil45/LS_Intro_to_ML_NLP/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 1

# Problem 1

In [1]:
!pip install --upgrade numpy

In [2]:
import numpy as np

arr = np.random.randint(1, 50, size=(5, 4))
print(arr)

[[24 49 17  2]
 [ 3  5 28  3]
 [ 1 24 26 29]
 [16 37 14 47]
 [48 31 30  1]]


In [3]:
print(np.max(arr, axis=1))
print(np.mean(arr))

[49 28 29 47 48]
21.75


In [4]:
new_arr = np.random.randint(1, np.mean(arr), size = (5,4))
print (new_arr)

[[13  6  4 18]
 [ 1  1  3  3]
 [ 2  2 13 13]
 [11  2 14  6]
 [12 20  3 20]]


In [5]:
def numpy_boundary_traversal(matrix):
    # Ensure the input is a 2D NumPy array
    if not isinstance(matrix, np.ndarray) or matrix.ndim != 2:
        raise ValueError("Input must be a 2D NumPy array")

    rows, cols = matrix.shape
    result = []

    if rows == 0 or cols == 0:
        return result

    # Top row
    for j in range(cols):
        result.append(matrix[0, j])

    # Right column (excluding first and last row if exists)
    for i in range(1, rows - 1):
        result.append(matrix[i, cols - 1])

    # Bottom row (only if more than 1 row)
    if rows > 1:
        for j in range(cols - 1, -1, -1):
            result.append(matrix[rows - 1, j])

    # Left column (excluding first and last row if exists)
    if cols > 1:
        for i in range(rows - 2, 0, -1):
            result.append(matrix[i, 0])

    return result


In [6]:
print( numpy_boundary_traversal(new_arr))

[np.int64(13), np.int64(6), np.int64(4), np.int64(18), np.int64(3), np.int64(13), np.int64(6), np.int64(20), np.int64(3), np.int64(20), np.int64(12), np.int64(11), np.int64(2), np.int64(1)]


# Problem 2

In [7]:
import numpy as np

In [8]:
arr1 = np.random.rand(20)
arr2 = np.multiply(arr1, 10)
print(arr2)

[5.65891523 6.68884715 1.91271353 2.51057757 1.42376425 6.29151937
 6.0064595  9.94688945 4.75606865 1.80371704 0.07433297 7.54050997
 5.92758984 0.3442321  4.79177199 1.77565019 4.36207987 1.91771685
 9.90955964 1.15467172]


In [9]:
print(np.min(arr2))
print(np.max(arr2))
print(np.median(arr2))

0.07433296620048213
9.946889445088944
4.559074257473112


In [10]:
arr3 = arr2.copy()
arr3[arr3 < 5] = arr3[arr3 < 5]**2
print(arr3)

[5.65891523e+00 6.68884715e+00 3.65847304e+00 6.30299974e+00
 2.02710465e+00 6.29151937e+00 6.00645950e+00 9.94688945e+00
 2.26201890e+01 3.25339516e+00 5.52538986e-03 7.54050997e+00
 5.92758984e+00 1.18495736e-01 2.29610788e+01 3.15293358e+00
 1.90277408e+01 3.67763793e+00 9.90955964e+00 1.33326678e+00]


In [11]:
def numpy_alternate_sort(array):
    sorted_array = np.sort(array)
    result = []

    left = 0
    right = len(sorted_array) - 1

    while left <= right:
        result.append(sorted_array[left])
        left += 1
        if left <= right:
            result.append(sorted_array[right])
            right -= 1

    return np.array(result)

print(numpy_alternate_sort(arr3))


[5.52538986e-03 2.29610788e+01 1.18495736e-01 2.26201890e+01
 1.33326678e+00 1.90277408e+01 2.02710465e+00 9.94688945e+00
 3.15293358e+00 9.90955964e+00 3.25339516e+00 7.54050997e+00
 3.65847304e+00 6.68884715e+00 3.67763793e+00 6.30299974e+00
 5.65891523e+00 6.29151937e+00 5.92758984e+00 6.00645950e+00]


# Problem 3

In [12]:
import pandas as pd
import numpy as np # Import numpy to use np.random.randint

dict = {'name':["aparna", "pankaj", "sudhir", "Geeku","varun","tanuj","milin","rahul","rohit","sahil"],
        'subject': ["phy", "chem", "chem", "Math","phy", "chem", "Math", "Math","phy","Math"],
        'score':np.random.randint(50,100, size=(10,)), # Changed shape to (10,)
        'Grade':[None]*10}

df = pd.DataFrame(dict)

print(df)

     name subject  score Grade
0  aparna     phy     88  None
1  pankaj    chem     53  None
2  sudhir    chem     99  None
3   Geeku    Math     76  None
4   varun     phy     64  None
5   tanuj    chem     79  None
6   milin    Math     73  None
7   rahul    Math     59  None
8   rohit     phy     64  None
9   sahil    Math     72  None


In [13]:
def get_grade(score):
    if score > 90:
        return 'A'
    elif score > 80:
        return 'B'
    elif score > 70:
        return 'C'
    elif score > 60:
        return 'D'
    else:
        return 'F'

# Assuming your DataFrame already exists with score column
df['Grade'] = df['score'].apply(get_grade)

print(df)


     name subject  score Grade
0  aparna     phy     88     B
1  pankaj    chem     53     F
2  sudhir    chem     99     A
3   Geeku    Math     76     C
4   varun     phy     64     D
5   tanuj    chem     79     C
6   milin    Math     73     C
7   rahul    Math     59     F
8   rohit     phy     64     D
9   sahil    Math     72     C


In [14]:
aggregated_data = df.groupby(['subject']).agg(
    avg_score=('score', 'mean')
  )

print(aggregated_data)

         avg_score
subject           
Math          70.0
chem          77.0
phy           72.0


In [15]:
def pandas_filter_pass(dataframe):
    # Filter rows where Grade is 'A' or 'B'
    return dataframe[dataframe['Grade'].isin(['A', 'B'])].copy()

passed_df = pandas_filter_pass(df)
print(passed_df)

     name subject  score Grade
0  aparna     phy     88     B
2  sudhir    chem     99     A


# Problem 4

In [16]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [17]:
# Step 1: Create synthetic dataset
positive_reviews = [f"This movie was excellent #{i}" for i in range(50)]
negative_reviews = [f"Terrible movie, very boring. #{i}" for i in range(50)]

reviews = positive_reviews + negative_reviews
sentiments = ['positive'] * 50 + ['negative'] * 50

df = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})

In [18]:
# Step 2: Tokenize using CountVectorizer
vectorizer = CountVectorizer(stop_words='english', max_features=500)
X = vectorizer.fit_transform(df['Review'])
y = df['Sentiment']


In [19]:
# Step 3: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Train Naive Bayes model
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [20]:
# Step 5: Evaluate accuracy
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")


Accuracy: 1.0


In [21]:
# Step 6: Define prediction function
def predict_review_sentiment(model, vectorizer, review):
    review_vec = vectorizer.transform([review])
    prediction = model.predict(review_vec)[0]
    return prediction
example_review = "The movie was really bad and I hated the characters."
predicted = predict_review_sentiment(model, vectorizer, example_review)
print(f"Predicted sentiment: {predicted}")

Predicted sentiment: positive


# Problem 5

In [22]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Step 1: Create synthetic dataset
good_feedback = [f"This product is great! I love it. #{i}" for i in range(50)]
bad_feedback = [f"Terrible quality. I hate this product. #{i}" for i in range(50)]

texts = good_feedback + bad_feedback
labels = ['good'] * 50 + ['bad'] * 50

df = pd.DataFrame({'Feedback': texts, 'Label': labels})

In [23]:
# Step 2: Preprocess using TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words='english', lowercase=True, max_features=300)
X = vectorizer.fit_transform(df['Feedback'])
y = df['Label']

# Step 3: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [24]:
# Step 4: Train Logistic Regression model
model = LogisticRegression()
model.fit(X_train, y_train)

# Step 5: Evaluate performance
y_pred = model.predict(X_test)
print("Classification Report:\n")
print(classification_report(y_test, y_pred, target_names=['good', 'bad']))

Classification Report:

              precision    recall  f1-score   support

        good       1.00      1.00      1.00        11
         bad       1.00      1.00      1.00        14

    accuracy                           1.00        25
   macro avg       1.00      1.00      1.00        25
weighted avg       1.00      1.00      1.00        25



In [25]:
# Step 6: Define vectorization function
def text_preprocess_vectorize(texts, vectorizer):
    """
    Vectorize a list of text samples using the given fitted TfidfVectorizer.
    """
    return vectorizer.transform(texts)

# Example usage
sample_texts = ["Amazing quality!", "Very poor and disappointing."]
vectorized_samples = text_preprocess_vectorize(sample_texts, vectorizer)
print("\nVectorized matrix shape:", vectorized_samples.shape)



Vectorized matrix shape: (2, 46)
